<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class DistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('districts')->insert([
            ['district_code'=>'0101','province_code'=>'01','district_title_1'=>'Serei Saophoan','district_title_2'=>'សិរីសោភ័ណ'],
            ['district_code'=>'0102','province_code'=>'01','district_title_1'=>'Poipet','district_title_2'=>'ប៉ោយប៉ែត'],
            ['district_code'=>'0103','province_code'=>'01','district_title_1'=>'Mongkol Borey','district_title_2'=>'មង្គលបូរី'],
            ['district_code'=>'0104','province_code'=>'01','district_title_1'=>'Phnom Srok','district_title_2'=>'ភ្នំស្រុក'],
            ['district_code'=>'0105','province_code'=>'01','district_title_1'=>'Preah Netr Preah','district_title_2'=>'ព្រះនេត្រព្រះ'],
            ['district_code'=>'0106','province_code'=>'01','district_title_1'=>'Ou Chrov','district_title_2'=>'អូរជ្រៅ'],
            ['district_code'=>'0107','province_code'=>'01','district_title_1'=>'Thma Puok','district_title_2'=>'ថ្មពួក'],
            ['district_code'=>'0108','province_code'=>'01','district_title_1'=>'Svay Chek','district_title_2'=>'ស្វាយចេក'],
            ['district_code'=>'0109','province_code'=>'01','district_title_1'=>'Malai','district_title_2'=>'ម៉ាឡៃ'],
            ['district_code'=>'0201','province_code'=>'02','district_title_1'=>'Battambang','district_title_2'=>'បាត់ដំបង'],
            ['district_code'=>'0202','province_code'=>'02','district_title_1'=>'Banan','district_title_2'=>'បាណន់'],
            ['district_code'=>'0203','province_code'=>'02','district_title_1'=>'Thma Koul','district_title_2'=>'ថ្មគោល'],
            ['district_code'=>'0204','province_code'=>'02','district_title_1'=>'Bavel','district_title_2'=>'បវែល'],
            ['district_code'=>'0205','province_code'=>'02','district_title_1'=>'Aek Phnom','district_title_2'=>'ឯកភ្នំ'],
            ['district_code'=>'0206','province_code'=>'02','district_title_1'=>'Moung Ruessei','district_title_2'=>'មោងឫស្សី'],
            ['district_code'=>'0207','province_code'=>'02','district_title_1'=>'Rotanak Mondol','district_title_2'=>'រតនមណ្ឌល'],
            ['district_code'=>'0208','province_code'=>'02','district_title_1'=>'Sangkae','district_title_2'=>'សង្កែ'],
            ['district_code'=>'0209','province_code'=>'02','district_title_1'=>'Samlout','district_title_2'=>'សំឡូត'],
            ['district_code'=>'0210','province_code'=>'02','district_title_1'=>'Sampov Loun','district_title_2'=>'សំពៅលូន'],
            ['district_code'=>'0211','province_code'=>'02','district_title_1'=>'Phnum Proek','district_title_2'=>'ភ្នំព្រឹក'],
            ['district_code'=>'0212','province_code'=>'02','district_title_1'=>'Kamrieng','district_title_2'=>'កំរៀង'],
            ['district_code'=>'0213','province_code'=>'02','district_title_1'=>'Koas Krala','district_title_2'=>'គាស់ក្រឡ'],
            ['district_code'=>'0214','province_code'=>'02','district_title_1'=>'Rukhak Kiri','district_title_2'=>'រុក្ខគិរី'],
            ['district_code'=>'0301','province_code'=>'03','district_title_1'=>'Kampong Cham','district_title_2'=>'កំពង់ចាម'],
            ['district_code'=>'0302','province_code'=>'03','district_title_1'=>'Batheay','district_title_2'=>'បាធាយ'],
            ['district_code'=>'0303','province_code'=>'03','district_title_1'=>'Chamkar Loeu','district_title_2'=>'ចំការលើ'],
            ['district_code'=>'0304','province_code'=>'03','district_title_1'=>'Cheung Prey','district_title_2'=>'ជើងព្រៃ'],
            ['district_code'=>'0305','province_code'=>'03','district_title_1'=>'Kampong Siem','district_title_2'=>'កំពង់សៀម'],
            ['district_code'=>'0306','province_code'=>'03','district_title_1'=>'Kang Meas','district_title_2'=>'កងមាស'],
            ['district_code'=>'0307','province_code'=>'03','district_title_1'=>'Koh Sotin','district_title_2'=>'កោះសូទិន'],
            ['district_code'=>'0308','province_code'=>'03','district_title_1'=>'Prey Chhor','district_title_2'=>'ព្រៃឈរ'],
            ['district_code'=>'0309','province_code'=>'03','district_title_1'=>'Srey Santhor','district_title_2'=>'ស្រីសន្ធរ'],
            ['district_code'=>'0310','province_code'=>'03','district_title_1'=>'Steung Trang','district_title_2'=>'ស្ទឹងត្រង់'],
            ['district_code'=>'0401','province_code'=>'04','district_title_1'=>'Baribo','district_title_2'=>'ស្រុកបរិបូណ៌'],
            ['district_code'=>'0402','province_code'=>'04','district_title_1'=>'Chol Kiri','district_title_2'=>'ស្រុកជលគីរី'],
            ['district_code'=>'0403','province_code'=>'04','district_title_1'=>'Kampong Chhnang Municipality','district_title_2'=>'ក្រុងកំពង់ឆ្នាំង'],
            ['district_code'=>'0404','province_code'=>'04','district_title_1'=>'Kampong Leng','district_title_2'=>'ស្រុកកំពង់លែង'],
            ['district_code'=>'0405','province_code'=>'04','district_title_1'=>'Kampong Tralach','district_title_2'=>'ស្រុកកំពង់ត្រឡាច'],
            ['district_code'=>'0406','province_code'=>'04','district_title_1'=>'Rolea Bier','district_title_2'=>'ស្រុករលាប្អៀរ'],
            ['district_code'=>'0407','province_code'=>'04','district_title_1'=>'Samakki Meanchey','district_title_2'=>'ស្រុកសាមគ្គីមានជ័យ'],
            ['district_code'=>'0408','province_code'=>'04','district_title_1'=>'Teuk Phos','district_title_2'=>'ស្រុកទឹកផុស'],
            ['district_code'=>'0501','province_code'=>'05','district_title_1'=>'Basedth','district_title_2'=>'ស្រុកបរសេដ្ឋ'],
            ['district_code'=>'0502','province_code'=>'05','district_title_1'=>'Chbar Mon Municipality','district_title_2'=>'ក្រុងច្បារមន'],
            ['district_code'=>'0503','province_code'=>'05','district_title_1'=>'Kong Pisei','district_title_2'=>'ស្រុកគងពិសី'],
            ['district_code'=>'0504','province_code'=>'05','district_title_1'=>'Aoral','district_title_2'=>'ស្រុកឱរ៉ាល់'],
            ['district_code'=>'0505','province_code'=>'05','district_title_1'=>'Oudong','district_title_2'=>'ស្រុកឧដុង្គ'],
            ['district_code'=>'0506','province_code'=>'05','district_title_1'=>'Phnom Sruoch','district_title_2'=>'ស្រុកភ្នំស្រួច'],
            ['district_code'=>'0507','province_code'=>'05','district_title_1'=>'Samraong Tong','district_title_2'=>'ស្រុកសំរោងទង'],
            ['district_code'=>'0508','province_code'=>'05','district_title_1'=>'Thpong','district_title_2'=>'ស្រុកថ្ពង'],
            ['district_code'=>'0601','province_code'=>'06','district_title_1'=>'Baray','district_title_2'=>'ស្រុកបារាយណ៍'],
            ['district_code'=>'0602','province_code'=>'06','district_title_1'=>'Kampong Svay','district_title_2'=>'ស្រុកកំពង់ស្វាយ'],
            ['district_code'=>'0603','province_code'=>'06','district_title_1'=>'Steung Saen Municipality','district_title_2'=>'ក្រុងស្ទឹងសែន'],
            ['district_code'=>'0604','province_code'=>'06','district_title_1'=>'Prasat Balangk','district_title_2'=>'ស្រុកប្រាសាទបល្ល័ង្ក'],
            ['district_code'=>'0605','province_code'=>'06','district_title_1'=>'Prasat Sambour','district_title_2'=>'ស្រុកប្រាសាទសំបូរ'],
            ['district_code'=>'0606','province_code'=>'06','district_title_1'=>'Sandaan','district_title_2'=>'ស្រុកសណ្ដាន់'],
            ['district_code'=>'0607','province_code'=>'06','district_title_1'=>'Santuk','district_title_2'=>'ស្រុកសន្ទុក'],
            ['district_code'=>'0608','province_code'=>'06','district_title_1'=>'Stoung','district_title_2'=>'ស្រុកស្ទោង'],
            ['district_code'=>'0609','province_code'=>'06','district_title_1'=>'Taing Kouk','district_title_2'=>'ស្រុកតាំងគោក'],
            ['district_code'=>'0701','province_code'=>'07','district_title_1'=>'Angkor Chey','district_title_2'=>'ស្រុកអង្គរជ័យ'],
            ['district_code'=>'0702','province_code'=>'07','district_title_1'=>'Banteay Meas','district_title_2'=>'ស្រុកបន្ទាយមាស'],
            ['district_code'=>'0703','province_code'=>'07','district_title_1'=>'Chhouk','district_title_2'=>'ស្រុកឈូក'],
            ['district_code'=>'0704','province_code'=>'07','district_title_1'=>'Chum Kiri','district_title_2'=>'ស្រុកជុំគិរី'],
            ['district_code'=>'0705','province_code'=>'07','district_title_1'=>'Dang Tong','district_title_2'=>'ស្រុកដងទង់'],
            ['district_code'=>'0706','province_code'=>'07','district_title_1'=>'Kampong Trach','district_title_2'=>'ស្រុកកំពង់ត្រាច'],
            ['district_code'=>'0707','province_code'=>'07','district_title_1'=>'Tuek Chhou','district_title_2'=>'ស្រុកទឹកឈូ'],
            ['district_code'=>'0708','province_code'=>'07','district_title_1'=>'Kampot Municipality','district_title_2'=>'ក្រុងកំពត'],
            ['district_code'=>'0801','province_code'=>'08','district_title_1'=>'Kandal Stueng','district_title_2'=>'កណ្ដាលស្ទឹង'],
            ['district_code'=>'0802','province_code'=>'08','district_title_1'=>'Kien Svay','district_title_2'=>'កៀនស្វាយ'],
            ['district_code'=>'0803','province_code'=>'08','district_title_1'=>'Khsach Kandal','district_title_2'=>'ខ្សាច់កណ្ដាល'],
            ['district_code'=>'0804','province_code'=>'08','district_title_1'=>'Kaoh Thum','district_title_2'=>'កោះធំ'],
            ['district_code'=>'0805','province_code'=>'08','district_title_1'=>'Leuk Daek','district_title_2'=>'លើកដែក'],
            ['district_code'=>'0806','province_code'=>'08','district_title_1'=>'Lvea Aem','district_title_2'=>'ល្វាឯម'],
            ['district_code'=>'0807','province_code'=>'08','district_title_1'=>'Mukh Kampul','district_title_2'=>'មុខកំពូល'],
            ['district_code'=>'0808','province_code'=>'08','district_title_1'=>'Angk Snuol','district_title_2'=>'អង្គស្នួល'],
            ['district_code'=>'0809','province_code'=>'08','district_title_1'=>'Ponhea Lueu','district_title_2'=>'ពញាឮ'],
            ['district_code'=>'0810','province_code'=>'08','district_title_1'=>'Sa ang','district_title_2'=>'ស្អាង'],
            ['district_code'=>'0811','province_code'=>'08','district_title_1'=>'Ta Khmau','district_title_2'=>'តាខ្មៅ'],
            ['district_code'=>'0812','province_code'=>'08','district_title_1'=>'Arey Ksat','district_title_2'=>'អរិយក្សត្រ'],
            ['district_code'=>'0901','province_code'=>'09','district_title_1'=>'Botum Sakor','district_title_2'=>'ស្រុកបទុមសាគរ'],
            ['district_code'=>'0902','province_code'=>'09','district_title_1'=>'Kiri Sakor','district_title_2'=>'ស្រុកគិរីសាគរ'],
            ['district_code'=>'0903','province_code'=>'09','district_title_1'=>'Koh Kong','district_title_2'=>'ស្រុកកោះកុង'],
            ['district_code'=>'0904','province_code'=>'09','district_title_1'=>'Khemarak Phoumin Municipality (formerly Smach Mean Chey)','district_title_2'=>'ក្រុងខេមរភូមិន្ទ (អតីត ស្រុកស្មាច់មានជ័យ)'],
            ['district_code'=>'0905','province_code'=>'09','district_title_1'=>'Mondol Seima','district_title_2'=>'ស្រុកមណ្ឌលសីមា'],
            ['district_code'=>'0906','province_code'=>'09','district_title_1'=>'Srae Ambel','district_title_2'=>'ស្រុកស្រែអំបិល'],
            ['district_code'=>'0907','province_code'=>'09','district_title_1'=>'Thma Bang','district_title_2'=>'ស្រុកថ្មបាំង'],
            ['district_code'=>'1001','province_code'=>'10','district_title_1'=>'Chhloung','district_title_2'=>'ឆ្លូង'],
            ['district_code'=>'1002','province_code'=>'10','district_title_1'=>'Kratié','district_title_2'=>'ក្រចេះ'],
            ['district_code'=>'1003','province_code'=>'10','district_title_1'=>'Preaek Prasab','district_title_2'=>'ព្រែកប្រសព្វ'],
            ['district_code'=>'1004','province_code'=>'10','district_title_1'=>'Sambour','district_title_2'=>'សំបូរ'],
            ['district_code'=>'1005','province_code'=>'10','district_title_1'=>'Snuol','district_title_2'=>'ស្នួល'],
            ['district_code'=>'1006','province_code'=>'10','district_title_1'=>'Chetr Borei','district_title_2'=>'ចិត្របុរី'],
            ['district_code'=>'1101','province_code'=>'11','district_title_1'=>'Senmonorom','district_title_2'=>'សែនមនោរម្យ'],
            ['district_code'=>'1102','province_code'=>'11','district_title_1'=>'Kaev Seima','district_title_2'=>'កែវសីមា'],
            ['district_code'=>'1103','province_code'=>'11','district_title_1'=>'Kaoh Nheaek','district_title_2'=>'កោះញែក'],
            ['district_code'=>'1104','province_code'=>'11','district_title_1'=>'Ou Reang','district_title_2'=>'អូររាំង'],
            ['district_code'=>'1105','province_code'=>'11','district_title_1'=>'Pechreada','district_title_2'=>'ពេជ្រាដា'],
            ['district_code'=>'1201','province_code'=>'12','district_title_1'=>'Chamkar Mon','district_title_2'=>'ខណ្ឌចំការមន'],
            ['district_code'=>'1202','province_code'=>'12','district_title_1'=>'Doun Penh','district_title_2'=>'ខណ្ឌដូនពេញ'],
            ['district_code'=>'1203','province_code'=>'12','district_title_1'=>'Prampir Makara','district_title_2'=>'ខណ្ឌប្រាំពីរមករា'],
            ['district_code'=>'1204','province_code'=>'12','district_title_1'=>'Tuol Kouk','district_title_2'=>'ខណ្ឌទួលគោក'],
            ['district_code'=>'1205','province_code'=>'12','district_title_1'=>'Dangkao','district_title_2'=>'ខណ្ឌដង្កោ'],
            ['district_code'=>'1206','province_code'=>'12','district_title_1'=>'Mean Chey','district_title_2'=>'ខណ្ឌមានជ័យ'],
            ['district_code'=>'1207','province_code'=>'12','district_title_1'=>'Russey Keo','district_title_2'=>'ខណ្ឌឫស្សីកែវ'],
            ['district_code'=>'1208','province_code'=>'12','district_title_1'=>'Sen Sok','district_title_2'=>'ខណ្ឌសែនសុខ'],
            ['district_code'=>'1209','province_code'=>'12','district_title_1'=>'Pou Senchey','district_title_2'=>'ខណ្ឌពោធិ៍សែនជ័យ'],
            ['district_code'=>'1210','province_code'=>'12','district_title_1'=>'Chroy Changvar','district_title_2'=>'ខណ្ឌជ្រោយចង្វារ'],
            ['district_code'=>'1211','province_code'=>'12','district_title_1'=>'Prek Pnov','district_title_2'=>'ខណ្ឌព្រែកព្នៅ'],
            ['district_code'=>'1212','province_code'=>'12','district_title_1'=>'Chbar Ampov','district_title_2'=>'ខណ្ឌច្បារអំពៅ'],
            ['district_code'=>'1213','province_code'=>'12','district_title_1'=>'Boeng Keng Kang','district_title_2'=>'ខណ្ឌបឹងកេងកង'],
            ['district_code'=>'1214','province_code'=>'12','district_title_1'=>'Kamboul','district_title_2'=>'ខណ្ឌកំបូល'],
            ['district_code'=>'1301','province_code'=>'13','district_title_1'=>'Chey Saen','district_title_2'=>'ស្រុកជ័យសែន'],
            ['district_code'=>'1302','province_code'=>'13','district_title_1'=>'Chhaeb','district_title_2'=>'ស្រុកឆែប'],
            ['district_code'=>'1303','province_code'=>'13','district_title_1'=>'Choam Khsant','district_title_2'=>'ស្រុកជាំក្សាន្ត'],
            ['district_code'=>'1304','province_code'=>'13','district_title_1'=>'Kuleaen','district_title_2'=>'ស្រុកគូលែន'],
            ['district_code'=>'1305','province_code'=>'13','district_title_1'=>'Rovieng','district_title_2'=>'ស្រុករវៀង'],
            ['district_code'=>'1306','province_code'=>'13','district_title_1'=>'Sangkom Thmei','district_title_2'=>'ស្រុកសង្គមថ្មី'],
            ['district_code'=>'1307','province_code'=>'13','district_title_1'=>'Tbaeng Meanchey','district_title_2'=>'ស្រុកត្បែងមានជ័យ'],
            ['district_code'=>'1308','province_code'=>'13','district_title_1'=>'Preah Vihear Municipality','district_title_2'=>'ក្រុងព្រះវិហារ'],
            ['district_code'=>'1401','province_code'=>'14','district_title_1'=>'Ba Phnum','district_title_2'=>'ស្រុកបាភ្នំ'],
            ['district_code'=>'1402','province_code'=>'14','district_title_1'=>'Kamchay Mear','district_title_2'=>'ស្រុកកំចាយមារ'],
            ['district_code'=>'1403','province_code'=>'14','district_title_1'=>'Kampong Trabaek','district_title_2'=>'ស្រុកកំពង់ត្របែក'],
            ['district_code'=>'1404','province_code'=>'14','district_title_1'=>'Kanhchriech','district_title_2'=>'ស្រុកកញ្ជ្រៀច'],
            ['district_code'=>'1405','province_code'=>'14','district_title_1'=>'Me Sang','district_title_2'=>'ស្រុកមេសាង'],
            ['district_code'=>'1406','province_code'=>'14','district_title_1'=>'Peam Chor','district_title_2'=>'ស្រុកពាមជរ'],
            ['district_code'=>'1407','province_code'=>'14','district_title_1'=>'Peam Ro','district_title_2'=>'ស្រុកពាមរក៍'],
            ['district_code'=>'1408','province_code'=>'14','district_title_1'=>'Pea Reang','district_title_2'=>'ស្រុកពារាំង'],
            ['district_code'=>'1409','province_code'=>'14','district_title_1'=>'Preah Sdach','district_title_2'=>'ស្រុកព្រះស្ដេច'],
            ['district_code'=>'1410','province_code'=>'14','district_title_1'=>'Prey Veng Municipality','district_title_2'=>'ក្រុងព្រៃវែង'],
            ['district_code'=>'1411','province_code'=>'14','district_title_1'=>'Pur Rieng','district_title_2'=>'ស្រុកពោធិ៍រៀង'],
            ['district_code'=>'1412','province_code'=>'14','district_title_1'=>'Sithor Kandal','district_title_2'=>'ស្រុកស៊ីធរកណ្ដាល'],
            ['district_code'=>'1413','province_code'=>'14','district_title_1'=>'Svay Antor[citation needed]','district_title_2'=>'ស្រុកស្វាយអន្ទរ'],
            ['district_code'=>'1501','province_code'=>'15','district_title_1'=>'44941','district_title_2'=>'Bakan'],
            ['district_code'=>'1502','province_code'=>'15','district_title_1'=>'44972','district_title_2'=>'Kandieng'],
            ['district_code'=>'1503','province_code'=>'15','district_title_1'=>'45000','district_title_2'=>'Krakor'],
            ['district_code'=>'1504','province_code'=>'15','district_title_1'=>'45031','district_title_2'=>'Phnum Kravanh'],
            ['district_code'=>'1505','province_code'=>'15','district_title_1'=>'45061','district_title_2'=>'Pursat Municipality (formerly Sampov Meas)'],
            ['district_code'=>'1506','province_code'=>'15','district_title_1'=>'45092','district_title_2'=>'Veal Veang'],
            ['district_code'=>'1507','province_code'=>'15','district_title_1'=>'45122','district_title_2'=>'Talou Senchey'],
            ['district_code'=>'1601','province_code'=>'16','district_title_1'=>'Andoung Meas','district_title_2'=>'អណ្ដូងមាស'],
            ['district_code'=>'1602','province_code'=>'16','district_title_1'=>'Banlung Municipality','district_title_2'=>'ទីក្រុងបានលុង'],
            ['district_code'=>'1603','province_code'=>'16','district_title_1'=>'Bar Kaev','district_title_2'=>'បាកែវ'],
            ['district_code'=>'1604','province_code'=>'16','district_title_1'=>'Koun Mom','district_title_2'=>'កួនមុំ'],
            ['district_code'=>'1605','province_code'=>'16','district_title_1'=>'Lumphat','district_title_2'=>'លំផាត់'],
            ['district_code'=>'1606','province_code'=>'16','district_title_1'=>'Ou Chum','district_title_2'=>'អ៊ូជុំ'],
            ['district_code'=>'1607','province_code'=>'16','district_title_1'=>'Ou Ya Dav','district_title_2'=>'អ៊ូយ៉ាដាវ'],
            ['district_code'=>'1608','province_code'=>'16','district_title_1'=>'Ta Veaeng','district_title_2'=>'តាវែង'],
            ['district_code'=>'1609','province_code'=>'16','district_title_1'=>'Veun Sai','district_title_2'=>'វឿនសៃ'],
            ['district_code'=>'1701','province_code'=>'17','district_title_1'=>'Siem Reap','district_title_2'=>'សៀមរាប'],
            ['district_code'=>'1702','province_code'=>'17','district_title_1'=>'Angkor Chum','district_title_2'=>'អង្គរជុំ'],
            ['district_code'=>'1703','province_code'=>'17','district_title_1'=>'Angkor Thom','district_title_2'=>'អង្គរធំ'],
            ['district_code'=>'1704','province_code'=>'17','district_title_1'=>'Banteay Srei','district_title_2'=>'បន្ទាយស្រី'],
            ['district_code'=>'1705','province_code'=>'17','district_title_1'=>'Chi Kraeng','district_title_2'=>'ជីក្រែង'],
            ['district_code'=>'1706','province_code'=>'17','district_title_1'=>'Kralanh','district_title_2'=>'ក្រឡាញ់'],
            ['district_code'=>'1707','province_code'=>'17','district_title_1'=>'Puok','district_title_2'=>'ពួក'],
            ['district_code'=>'1708','province_code'=>'17','district_title_1'=>'Prasat Bakong','district_title_2'=>'ប្រាសាទបាគង'],
            ['district_code'=>'1709','province_code'=>'17','district_title_1'=>'Soutr Nikom','district_title_2'=>'សូត្រនិគម'],
            ['district_code'=>'1710','province_code'=>'17','district_title_1'=>'Srei Snam','district_title_2'=>'ស្រីស្នម'],
            ['district_code'=>'1711','province_code'=>'17','district_title_1'=>'Svay Leu','district_title_2'=>'ស្វាយលើ'],
            ['district_code'=>'1712','province_code'=>'17','district_title_1'=>'Varin','district_title_2'=>'វ៉ារិន'],
            ['district_code'=>'1801','province_code'=>'18','district_title_1'=>'Sihanoukville Municipality','district_title_2'=>'ក្រុងព្រះសីហនុ (អតីត ស្រុកមិត្តភាព'],
            ['district_code'=>'1802','province_code'=>'18','district_title_1'=>'Prey Nob','district_title_2'=>'ព្រៃនប់'],
            ['district_code'=>'1803','province_code'=>'18','district_title_1'=>'Stueng Hav','district_title_2'=>'ស្ទឹងហាវ'],
            ['district_code'=>'1804','province_code'=>'18','district_title_1'=>'Kampong Seila','district_title_2'=>'កំពង់សីលា'],
            ['district_code'=>'1901','province_code'=>'19','district_title_1'=>'Sesan','district_title_2'=>'ស្រុកសេសាន'],
            ['district_code'=>'1902','province_code'=>'19','district_title_1'=>'Siem Bouk','district_title_2'=>'ស្រុកសៀមបូក'],
            ['district_code'=>'1903','province_code'=>'19','district_title_1'=>'Siem Pang','district_title_2'=>'ស្រុកសៀមប៉ាង'],
            ['district_code'=>'1904','province_code'=>'19','district_title_1'=>'Stung Treng Municipality','district_title_2'=>'ក្រុងស្ទឹងត្រែង'],
            ['district_code'=>'1905','province_code'=>'19','district_title_1'=>'Thala Barivat','district_title_2'=>'ស្រុកថាឡាបរិវ៉ាត់'],
            ['district_code'=>'1906','province_code'=>'19','district_title_1'=>'Borei O Svay Sen Chey','district_title_2'=>'ស្រុកបុរីអូរស្វាយសែនជ័យ'],
            ['district_code'=>'2001','province_code'=>'20','district_title_1'=>'Chantrea','district_title_2'=>'ស្រុកចន្ទ្រា'],
            ['district_code'=>'2002','province_code'=>'20','district_title_1'=>'Kampong Rou','district_title_2'=>'ស្រុកកំពង់រោទិ៍'],
            ['district_code'=>'2003','province_code'=>'20','district_title_1'=>'Rumduol','district_title_2'=>'ស្រុករំដួល'],
            ['district_code'=>'2004','province_code'=>'20','district_title_1'=>'Romeas Haek','district_title_2'=>'ស្រុករមាសហែក'],
            ['district_code'=>'2005','province_code'=>'20','district_title_1'=>'Svay Chrum','district_title_2'=>'ស្រុកស្វាយជ្រំ'],
            ['district_code'=>'2006','province_code'=>'20','district_title_1'=>'Svay Rieng Municipality','district_title_2'=>'ក្រុងស្វាយរៀង'],
            ['district_code'=>'2007','province_code'=>'20','district_title_1'=>'Svay Teab','district_title_2'=>'ស្រុកស្វាយទាប'],
            ['district_code'=>'2008','province_code'=>'20','district_title_1'=>'Bavet Municipality','district_title_2'=>'ក្រុងបាវិត'],
            ['district_code'=>'2101','province_code'=>'21','district_title_1'=>'Angkor Borei','district_title_2'=>'ស្រុកអង្គរបូរី'],
            ['district_code'=>'2102','province_code'=>'21','district_title_1'=>'Bati','district_title_2'=>'ស្រុកបាទី'],
            ['district_code'=>'2103','province_code'=>'21','district_title_1'=>'Bourei Cholsar','district_title_2'=>'ស្រុកបូរីជលសារ'],
            ['district_code'=>'2104','province_code'=>'21','district_title_1'=>'Kiri Vong','district_title_2'=>'ស្រុកគិរីវង់'],
            ['district_code'=>'2105','province_code'=>'21','district_title_1'=>'Koh Andaet','district_title_2'=>'ស្រុកកោះអណ្ដែត'],
            ['district_code'=>'2106','province_code'=>'21','district_title_1'=>'Prey Kabbas','district_title_2'=>'ស្រុកព្រៃកប្បាស'],
            ['district_code'=>'2107','province_code'=>'21','district_title_1'=>'Samraŏng','district_title_2'=>'ស្រុកសំរោង'],
            ['district_code'=>'2108','province_code'=>'21','district_title_1'=>'Doun Kaev Municipality','district_title_2'=>'ក្រុងដូនកែវ'],
            ['district_code'=>'2109','province_code'=>'21','district_title_1'=>'Tram Kak','district_title_2'=>'ស្រុកត្រាំកក់'],
            ['district_code'=>'2110','province_code'=>'21','district_title_1'=>'Treang','district_title_2'=>'ស្រុកទ្រាំង'],
            ['district_code'=>'2201','province_code'=>'22','district_title_1'=>'Samraong','district_title_2'=>'សំរោង'],
            ['district_code'=>'2202','province_code'=>'22','district_title_1'=>'Anlong Veng','district_title_2'=>'អន្លង់វែង'],
            ['district_code'=>'2203','province_code'=>'22','district_title_1'=>'Banteay Ampil','district_title_2'=>'បន្ទាយអំពិល'],
            ['district_code'=>'2204','province_code'=>'22','district_title_1'=>'Chong Kal','district_title_2'=>'ចុងកាល'],
            ['district_code'=>'2205','province_code'=>'22','district_title_1'=>'Trapeang Prasat','district_title_2'=>'ត្រពាំងប្រាសាទ'],
            ['district_code'=>'2301','province_code'=>'23','district_title_1'=>'Damnak Chang aeur','district_title_2'=>'ស្រុកដំណាក់ចង្អើរ'],
            ['district_code'=>'2302','province_code'=>'23','district_title_1'=>'Kep Municipality','district_title_2'=>'ក្រុងកែប'],
            ['district_code'=>'2401','province_code'=>'24','district_title_1'=>'Pailin','district_title_2'=>'ប៉ែលិន'],
            ['district_code'=>'2402','province_code'=>'24','district_title_1'=>'Sala Krau','district_title_2'=>'សាលាក្រៅ'],
            ['district_code'=>'2501','province_code'=>'25','district_title_1'=>'Dambae','district_title_2'=>'ស្រុកតំបែរ'],
            ['district_code'=>'2502','province_code'=>'25','district_title_1'=>'Krouch Chhmar','district_title_2'=>'ស្រុកក្រូចឆ្មារ'],
            ['district_code'=>'2503','province_code'=>'25','district_title_1'=>'Memot','district_title_2'=>'ស្រុកមេមត់'],
            ['district_code'=>'2504','province_code'=>'25','district_title_1'=>'Ou Reang Ov','district_title_2'=>'ស្រុកអូររាំងឪ'],
            ['district_code'=>'2505','province_code'=>'25','district_title_1'=>'Ponhea Kraek','district_title_2'=>'ស្រុកពញាក្រែក'],
            ['district_code'=>'2506','province_code'=>'25','district_title_1'=>'Tboung Khmum','district_title_2'=>'ស្រុកត្បូងឃ្មុំ'],
            ['district_code'=>'2507','province_code'=>'25','district_title_1'=>'Suong Municipality','district_title_2'=>'ក្រុងសួង'],
               
        ]);
    }
}
