<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class JobSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('jobs')->insert([
            ['job_code'=>'1041','job_title_1'=>' Senior military and policer officials','job_title_2'=>'មន្រ្តីយោធា ប៉ូលីស ទាហ៊ាន ជាន់ខ្ពស់ (រាប់ចាប់ពី ផ្កាយ១ឡើងទៅ)'],
            ['job_code'=>'1059','job_title_1'=>'Accounting','job_title_2'=>'ផ្នែកគណនេយ្យ ( គណនេយ្យករ​ ឬក្រុមហ៊ុនផ្នែកគណនី)'],
            ['job_code'=>'1146','job_title_1'=>'Agri-Equips/machines TR','job_title_2'=>'លក់រាយឧបករណ៍/គ្រឿងម៉ាស៊ីនកសិកម្ម'],
            ['job_code'=>'1223','job_title_1'=>'Agri-input trading wholesale','job_title_2'=>'បោះដុំសម្ភារៈកសិកម្ម'],
            ['job_code'=>'1246','job_title_1'=>'Agri-inputs (fertilizer/seeds) TI','job_title_2'=>'នាំចូលសម្ភារៈកសិកម្ម(ជី ពូជ...)'],
            ['job_code'=>'1245','job_title_1'=>'Agri-inputs (fertilizer/seeds) TR','job_title_2'=>'លក់រាយសម្ភារៈកសិកម្ម(ជី ពូជ...)'],
            ['job_code'=>'1194','job_title_1'=>'Animal Feed trading import','job_title_2'=>'នាំចូលចំណីសត្វ'],
            ['job_code'=>'1193','job_title_1'=>'Animal feed trading retail','job_title_2'=>'លក់រាយចំណីសត្វ'],
            ['job_code'=>'1232','job_title_1'=>'Animal Feed trading wholesale','job_title_2'=>'បោះដុំចំណីសត្វ'],
            ['job_code'=>'1084','job_title_1'=>'Banana plantation','job_title_2'=>'ធ្វើចំការចេក'],
            ['job_code'=>'1172','job_title_1'=>'Banana trading wholesale','job_title_2'=>'ជួញចេក'],
            ['job_code'=>'1217','job_title_1'=>'Bar / Pub','job_title_2'=>'បា ឬ ផាប់'],
            ['job_code'=>'1058','job_title_1'=>'Blue collar worker- Constr worker','job_title_2'=>'កម្មករសំណង់'],
            ['job_code'=>'1056','job_title_1'=>'Blue collar worker- garment worker','job_title_2'=>'កម្មកររោងចក្រ'],
            ['job_code'=>'1055','job_title_1'=>'Blue collar worker- other','job_title_2'=>'កម្មករផ្សេងៗទៀត'],
            ['job_code'=>'1222','job_title_1'=>'Boat Trans service-passenger','job_title_2'=>'សេវាដឹកអ្នកដំណើរតាមផ្លូវទឹក'],
            ['job_code'=>'1096','job_title_1'=>'Boat/Ferry','job_title_2'=>'កាណូត/ទូកចម្លង សាឡាងគ្រប់ប្រភេទ'],
            ['job_code'=>'1141','job_title_1'=>'Brick/tile/kiln','job_title_2'=>'សិប្បកម្មឡឥដ្ឋ/ក្បឿង'],
            ['job_code'=>'1157','job_title_1'=>'Broadcasting on TV/radio','job_title_2'=>'សេវាផ្សព្វផ្សាយតាមវិទ្យុ/ទូរទស្សន៍'],
            ['job_code'=>'1045','job_title_1'=>'Building Engineer','job_title_2'=>'វិស្វករសំណង់ (ផ្ទះ អាគារ ហេដ្ឋារចនាសម្ព័ន្ធ។ល។'],
            ['job_code'=>'1069','job_title_1'=>'Bus/Car Tour','job_title_2'=>'រថយន្តឈ្នួលសំរាប់ដឹកភ្ញៀវទេសចរណ៏គ្រប់ប្រភេទ'],
            ['job_code'=>'1184','job_title_1'=>'Car and Motorbike washing','job_title_2'=>'សេវាកម្មលាងរថយន្ត/ម៉ូតូ'],
            ['job_code'=>'1170','job_title_1'=>'Car repair shop','job_title_2'=>'សេវាជួសជុលរថយន្ត'],
            ['job_code'=>'1206','job_title_1'=>'Car Trans service-passenger','job_title_2'=>'សេវាដឹកជញ្ជូនអ្នកដំណើរតាមរថយន្ត'],
            ['job_code'=>'1183','job_title_1'=>'Carpentry','job_title_2'=>'សិប្បកម្មជាងឈើ'],
            ['job_code'=>'1125','job_title_1'=>'Cashew nut production','job_title_2'=>'ធ្វើចំការស្វាយចន្ទី'],
            ['job_code'=>'1049','job_title_1'=>'Casino or other gambling ','job_title_2'=>'កាស៊ីណូ ឬកន្លែងភ្នាល់ផ្សេងទៀត'],
            ['job_code'=>'1242','job_title_1'=>'Cassava production','job_title_2'=>'ធ្វើចំការដំឡូងមី'],
            ['job_code'=>'1186','job_title_1'=>'Cassava trading wholesale','job_title_2'=>'ជួញដំឡូងមី'],
            ['job_code'=>'1135','job_title_1'=>'Cassava trading-export','job_title_2'=>'នាំចេញដំឡូងមី'],
            ['job_code'=>'1256','job_title_1'=>'Chicken raising','job_title_2'=>'ចិញ្ចឹមមាន់'],
            ['job_code'=>'1209','job_title_1'=>'Chicken/duck trading retail','job_title_2'=>'ជួញរាយមាន់ទា'],
            ['job_code'=>'1253','job_title_1'=>'Clothes/wear apparel/leather Pro TE','job_title_2'=>'នាំចេញសំលៀកបំពាក់ និងផលិតផលពីស្បែក'],
            ['job_code'=>'1252','job_title_1'=>'Clothes/wear apparel/leather Pro TR','job_title_2'=>'លក់រាយសំលៀកបំពាក់ និងផលិតផលធ្វើពីស្បែក'],
            ['job_code'=>'1255','job_title_1'=>'Clothes/wearing apparel/leather Pro','job_title_2'=>'ផលិតសំលៀកបំពាក់ និងផលិតផលពីស្បែក'],
            ['job_code'=>'1248','job_title_1'=>'Clothes/wearing apparel/leather TI','job_title_2'=>'នាំចូលសំលៀកបំពាក់ និងផលិផលធ្វើពីស្បែក'],
            ['job_code'=>'1087','job_title_1'=>'Constr Equip making','job_title_2'=>'ផលិតសម្ភារៈបរិក្ខារសំណង់'],
            ['job_code'=>'1163','job_title_1'=>'Constr material TI','job_title_2'=>'នាំចូលសម្ភារៈសំណង់'],
            ['job_code'=>'1162','job_title_1'=>'Constr material TR','job_title_2'=>'លក់រាយសម្ភារៈសំណង់'],
            ['job_code'=>'1102','job_title_1'=>'Construction service','job_title_2'=>'សេវាសាងសង់សំណង់ផ្សេងៗ'],
            ['job_code'=>'1054','job_title_1'=>'Consultant','job_title_2'=>'អ្នកប្រឹក្សាយោបល់'],
            ['job_code'=>'1113','job_title_1'=>'Contract pig raising','job_title_2'=>'ចិញ្ចឹមជ្រូកមានកិច្ចសន្យាជាមួយក្រុមហ៊ុន'],
            ['job_code'=>'1200','job_title_1'=>'Contract poultices raising','job_title_2'=>'ចិញ្ចឹមបក្សីមានកិច្ចសន្យាជាមួយក្រុមហ៊ុន​(មាន់ ទា..)'],
            ['job_code'=>'1095','job_title_1'=>'Cow/buffalo raising','job_title_2'=>'ចិញ្ចឹមគោក្របី'],
            ['job_code'=>'1195','job_title_1'=>'Cow/buffalo trading retail','job_title_2'=>'ជួញរាយគោក្របី'],
            ['job_code'=>'1086','job_title_1'=>'Crop trading retail','job_title_2'=>'លក់រាយដំណាំ/ធញ្ញជាតិផ្សេងៗ'],
            ['job_code'=>'1091','job_title_1'=>'Crop trading-export','job_title_2'=>'នាំចេញដំណាំផ្សេងៗ'],
            ['job_code'=>'1050','job_title_1'=>'Customs or revenue officials.','job_title_2'=>'មន្ត្រីគយ ឬគ្រប់គ្រងចំណូលរដ្ឋ'],
            ['job_code'=>'1171','job_title_1'=>'Dental clinic','job_title_2'=>'សេវាព្យាបាលធ្មេញ'],
            ['job_code'=>'1103','job_title_1'=>'Detergent handicraft','job_title_2'=>'សិប្បកម្មផលិតសាប៊ូ'],
            ['job_code'=>'1066','job_title_1'=>'Door/window Manu','job_title_2'=>'សិប្បកម្មផលិតទ្វារ បង្អួច'],
            ['job_code'=>'1142','job_title_1'=>'Drinking','job_title_2'=>'ផលិតទឹកស្អាត/ភេសជ្ជៈ'],
            ['job_code'=>'1201','job_title_1'=>'Dry season rice production','job_title_2'=>'ធ្វើស្រែប្រាំង'],
            ['job_code'=>'1258','job_title_1'=>'Duck raising','job_title_2'=>'ចិញ្ចឹមទា'],
            ['job_code'=>'1079','job_title_1'=>'Durian plantation','job_title_2'=>'ធ្វើចំការធូរេន'],
            ['job_code'=>'1224','job_title_1'=>'Egg trading retail','job_title_2'=>'ជួញស៊ុត'],
            ['job_code'=>'1099','job_title_1'=>'Electricity supplier','job_title_2'=>'ផ្គត់ផ្គង់ចរន្តអគ្គីសនី'],
            ['job_code'=>'1148','job_title_1'=>'Electronic appliance TR','job_title_2'=>'លក់រាយគ្រឿងអគ្គីសនី'],
            ['job_code'=>'1132','job_title_1'=>'Electronic repair shop','job_title_2'=>'សេវាជួសជុលសម្ភារៈអគ្គីសនី'],
            ['job_code'=>'1178','job_title_1'=>'Entertainment','job_title_2'=>'សេវាកម្មកំសាន្ត'],
            ['job_code'=>'1231','job_title_1'=>'Family pig raising','job_title_2'=>'ចិញ្ចឹមជ្រូកលក្ខណៈគ្រួសារ'],
            ['job_code'=>'1149','job_title_1'=>'Firewood trading retail','job_title_2'=>'លក់ធ្យូង/អុស'],
            ['job_code'=>'1212','job_title_1'=>'Firework/exposive production','job_title_2'=>'ផាវ កាំជ្រួច ឬសកម្មភាពពាក់ព័ន្ធនឹងរំសេវ'],
            ['job_code'=>'1100','job_title_1'=>'Food and beverage TI','job_title_2'=>'នាំចូលអាហារ និងភេសជ្ជៈ'],
            ['job_code'=>'1260','job_title_1'=>'Food and Beverage trading wholesale','job_title_2'=>'បោះដុំអាហារ និងភេសជ្ជៈ'],
            ['job_code'=>'1240','job_title_1'=>'Food and beverage trading-export','job_title_2'=>'នាំចេញអាហារ និងភេសជ្ជៈ'],
            ['job_code'=>'1159','job_title_1'=>'Food supplier/restaurant','job_title_2'=>'សេវាផ្គត់ផ្គង់អាហារ/ភោជនីដ្ឋាន'],
            ['job_code'=>'1106','job_title_1'=>'Fruit trading import','job_title_2'=>'នាំចូលផ្លែឈើ'],
            ['job_code'=>'1105','job_title_1'=>'Fruit trading retail','job_title_2'=>'លក់រាយផ្លែឈើ'],
            ['job_code'=>'1109','job_title_1'=>'Furniture','job_title_2'=>'សិប្បកម្មផលិតគ្រឿងសង្ហារឹម'],
            ['job_code'=>'1266','job_title_1'=>'Future cashew nut trading wholesale','job_title_2'=>'ម៉ៅស្វាយចន្ទី'],
            ['job_code'=>'1241','job_title_1'=>'Future cassava trading wholesale','job_title_2'=>'ម៉ៅចំការដំឡូងមី'],
            ['job_code'=>'1236','job_title_1'=>'Future mango trading wholesale','job_title_2'=>'ម៉ៅស្វាយ'],
            ['job_code'=>'1175','job_title_1'=>'Gas supplier','job_title_2'=>'ផ្គត់ផ្គង់ឧស្ម័ន'],
            ['job_code'=>'1076','job_title_1'=>'Gasoline supplier','job_title_2'=>'ផ្គត់ផ្គង់ប្រេងសាំង'],
            ['job_code'=>'1143','job_title_1'=>'General clinic','job_title_2'=>'សេវាព្យាបាលជម្ងឺទូទៅ'],
            ['job_code'=>'1051','job_title_1'=>'Glasses/bowl/pot','job_title_2'=>'សិប្បកម្មផលិតក្អម/ចាន/ឆ្នាំង/កែវ'],
            ['job_code'=>'1227','job_title_1'=>'Goldsmith','job_title_2'=>'ជាងទង'],
            ['job_code'=>'1234','job_title_1'=>'Goods/Equipment Transportation','job_title_2'=>'រថយន្តដឹកទំនិញ​ និងគ្រឿងសំភារៈគ្រប់ប្រភេទ'],
            ['job_code'=>'1198','job_title_1'=>'Grocery-retail','job_title_2'=>'លក់គ្រឿងទេស'],
            ['job_code'=>'1156','job_title_1'=>'Guesthouse','job_title_2'=>'សេវាកម្មផ្ទះសំណាក់'],
            ['job_code'=>'1115','job_title_1'=>'Haircut- Salon','job_title_2'=>'សេវាកម្មកាត់សក់ កែសម្ភស្ស'],
            ['job_code'=>'1044','job_title_1'=>'Head/Deputy head of Gov/state','job_title_2'=>'ប្រមុខរដ្ឋ(ស្តីទី) ប្រមុខរាជរដ្ឋាភិបាល (ស្តីទី)'],
            ['job_code'=>'1168','job_title_1'=>'Hotel','job_title_2'=>'សេវាកម្មសណ្ឋាគារ'],
            ['job_code'=>'1265','job_title_1'=>'Housewife','job_title_2'=>'មេផ្ទះ'],
            ['job_code'=>'1062','job_title_1'=>'HR service/ Labour, Recruiters or Employment Website Agency','job_title_2'=>'មុខរបរទាក់ទងនឹងសេវាកម្មស្វែងរកការងារ/ភ្នាក់ងារជ្រើសរើសបុគ្គលិក/ភ្នាក់ងារបង្កើតគេហទំព័រស្វែងរកការងារ'],
            ['job_code'=>'1039','job_title_1'=>'Important political party officer ','job_title_2'=>'មន្រ្តីគណបក្សសំខាន់ៗ​ (រួមមាន ប្រធាន អនុប្រធាន គណៈកម្មាធិការបក្ស)'],
            ['job_code'=>'1094','job_title_1'=>'Inland fish raising','job_title_2'=>'ចិញ្ចឹមមច្ឆាទឹកសាប'],
            ['job_code'=>'1257','job_title_1'=>'Inland fishing','job_title_2'=>'នេសាទទឹកសាប'],
            ['job_code'=>'1230','job_title_1'=>'Inland fishing trading retail','job_title_2'=>'ជួញផលនេសាទទឹកសាប'],
            ['job_code'=>'1068','job_title_1'=>'Internet service','job_title_2'=>'សេវាកម្មអ៊ិនធ័រណេត'],
            ['job_code'=>'1082','job_title_1'=>'Jewelry/Gold and Precious Stones trading','job_title_2'=>'លក់គ្រឿងអលង្ការ/មាស និងត្បូងមានតំលៃ'],
            ['job_code'=>'1137','job_title_1'=>'Krama/silk weaving','job_title_2'=>'ត្បាញក្រម៉ា/ហូល/ផាមួង'],
            ['job_code'=>'1160','job_title_1'=>'Land Trans service-goods','job_title_2'=>'សេវាដឹកជញ្ជូនទំនិញតាមផ្លូវគោក'],
            ['job_code'=>'1110','job_title_1'=>'Laundry service','job_title_2'=>'សេវាកម្មបោកអ៊ុតសំលៀកបំពាក់'],
            ['job_code'=>'1061','job_title_1'=>'Lawyer','job_title_2'=>'មេធាវី'],
            ['job_code'=>'1042','job_title_1'=>'Local Authority (Village-District)','job_title_2'=>'អាជ្ញាធរថ្នាក់ភូមិ ឃុំ ស្រុក(មេភូមិ មេឃុំ អភិបាលស្រុក)'],
            ['job_code'=>'1121','job_title_1'=>'Machinery repair shop','job_title_2'=>'សេវាជួសជុលគ្រឿងម៉ាស៊ីន'],
            ['job_code'=>'1073','job_title_1'=>'Maize production','job_title_2'=>'ធ្វើចំការពោត'],
            ['job_code'=>'1154','job_title_1'=>'Maize trading wholesale','job_title_2'=>'ជួញពោត'],
            ['job_code'=>'1112','job_title_1'=>'Maize trading-export','job_title_2'=>'នាំចេញពោត'],
            ['job_code'=>'1104','job_title_1'=>'Make-up/beauty salon','job_title_2'=>'សំអាងការ/កែសម្ផស្ស'],
            ['job_code'=>'1072','job_title_1'=>'Mango plantation','job_title_2'=>'ធ្វើចំការស្វាយ​'],
            ['job_code'=>'1152','job_title_1'=>'Mango trading wholesale','job_title_2'=>'ជួញស្វាយ'],
            ['job_code'=>'1108','job_title_1'=>'Mango trading-export','job_title_2'=>'នាំចេញស្វាយ'],
            ['job_code'=>'1179','job_title_1'=>'Massage service','job_title_2'=>'សេវាកម្មម៉ាស្សា'],
            ['job_code'=>'1197','job_title_1'=>'Mat weaving','job_title_2'=>'ត្បាញកន្ទេល'],
            ['job_code'=>'1089','job_title_1'=>'Medical/pharmacy TI','job_title_2'=>'នាំចូលឪសថ/ថ្នាំពេទ្យ'],
            ['job_code'=>'1088','job_title_1'=>'Medical/pharmacy TR','job_title_2'=>'លក់រាយឪសថ/ថ្នាំពេទ្យ'],
            ['job_code'=>'1249','job_title_1'=>'Medical/pharmacy trading wholesale','job_title_2'=>'បោះដុំថ្នាំពេទ្យ/ឪសថ'],
            ['job_code'=>'1213','job_title_1'=>'Micro ice','job_title_2'=>'ផលិតទឹកកក'],
            ['job_code'=>'1043','job_title_1'=>'Military and Police officials','job_title_2'=>'មន្រ្តីយោធា ប៉ូលីស ទាហ៊ាន (រាប់ចាប់ពី ផ្កាយ១ ចុះ)'],
            ['job_code'=>'1199','job_title_1'=>'Milled rice trading import','job_title_2'=>'នាំចូលអង្ករ'],
            ['job_code'=>'1196','job_title_1'=>'Milled rice trading-retail','job_title_2'=>'លក់រាយអង្ករ'],
            ['job_code'=>'1233','job_title_1'=>'Milled rice trading-wholesale','job_title_2'=>'លក់ដុំអង្ករ'],
            ['job_code'=>'1219','job_title_1'=>'Money exchange dealer (MED).','job_title_2'=>'សេវាកម្មប្តូរប្រាក់/ផ្ទេរប្រាក់'],
            ['job_code'=>'1264','job_title_1'=>'Monk','job_title_2'=>'ព្រះសង្ឃ'],
            ['job_code'=>'1180','job_title_1'=>'Moto-Car Broker','job_title_2'=>'គួកជេរឡាន ម៉ូតូ'],
            ['job_code'=>'1181','job_title_1'=>'Motor/Motorbike Cart Taxi','job_title_2'=>'រត់ម៉ូតូឌុប ឬរត់ម៉ូតូរម៉ក់'],
            ['job_code'=>'1122','job_title_1'=>'Motorbike repair shop','job_title_2'=>'សេវាជួសជុលម៉ូតូ កង់'],
            ['job_code'=>'1114','job_title_1'=>'Mung bean production','job_title_2'=>'ធ្វើចំការសណ្តែកបាយ'],
            ['job_code'=>'1203','job_title_1'=>'Non agri-Equips/machines TR','job_title_2'=>'លក់ឧបករណ៍/ម៉ាស៊ីនមិនប្រើក្នុងវិស័យកសិកម្ម'],
            ['job_code'=>'1211','job_title_1'=>'Non-government organization','job_title_2'=>'អង្តការក្រៅរដ្ឋាភិបាល ឬមូលនិធិ'],
            ['job_code'=>'1090','job_title_1'=>'Optical care centre','job_title_2'=>'ហាងកាត់កញ្ចក់វ៉ែនតា'],
            ['job_code'=>'1208','job_title_1'=>'Other agricultural services','job_title_2'=>'សេវាកម្មកសិកម្មផ្សេងទៀត'],
            ['job_code'=>'1124','job_title_1'=>'Other animal raisings','job_title_2'=>'ចិញ្ចឹមសត្វពាហនៈផ្សេងៗទៀត'],
            ['job_code'=>'1207','job_title_1'=>'Other commercial product TR','job_title_2'=>'លក់រាយផលិតផលជំនួញផ្សេងទៀត'],
            ['job_code'=>'1126','job_title_1'=>'Other crop production','job_title_2'=>'ដាំដុះដំណាំផ្សេងៗ'],
            ['job_code'=>'1225','job_title_1'=>'Other Crop trading wholesale','job_title_2'=>'ជួញដុំដំណាំផ្សេងៗទៀត'],
            ['job_code'=>'1187','job_title_1'=>'Other crop/food processing','job_title_2'=>'កែច្នៃម្ហូបអាហារ/ដំណាំផ្សេងៗ'],
            ['job_code'=>'1173','job_title_1'=>'Other Financial Service ','job_title_2'=>'សេវាហិរញ្ញវត្ថុផ្សេងៗទៀត (ភ្នាក់ងារផ្តល់សេវាកម្មផ្ទេរប្រាក់ ជាដើម)'],
            ['job_code'=>'1145','job_title_1'=>'Other fruit production','job_title_2'=>'ធ្វើចំការឈើហូបផ្លែផ្សេងៗ'],
            ['job_code'=>'1229','job_title_1'=>'Other fruit trading wholesale','job_title_2'=>'ជួញដុំផ្លែឈើផ្សេងៗទៀត'],
            ['job_code'=>'1188','job_title_1'=>'Other future crop/fruit TW','job_title_2'=>'ម៉ៅដំណាំ/ផ្លែឈើផ្សេងៗទៀត'],
            ['job_code'=>'1052','job_title_1'=>'Other Independent professional ','job_title_2'=>'វិជ្ជាជីវៈឯករាជ្យផ្សេងទៀត'],
            ['job_code'=>'1235','job_title_1'=>'Other livestock trading retail','job_title_2'=>'ជួញរាយសត្វពាហនៈផ្សេងៗទៀត'],
            ['job_code'=>'1226','job_title_1'=>'Other local trading wholesale','job_title_2'=>'បោះដុំក្នុងស្រុក ទំនិញ/សម្ភារៈផ្សេងៗទៀត'],
            ['job_code'=>'1092','job_title_1'=>'Other Manufacturing','job_title_2'=>'សិប្បកម្មផ្សេងៗ'],
            ['job_code'=>'1204','job_title_1'=>'Other non-financial service','job_title_2'=>'សេវាកម្មមិនមែនហិរញ្ញវត្ថុផ្សេងៗទៀត'],
            ['job_code'=>'1144','job_title_1'=>'Other poultry raisings','job_title_2'=>'ចិញ្ចឹមសត្វស្លាបផ្សេងៗទៀត'],
            ['job_code'=>'1205','job_title_1'=>'Other real estate operation','job_title_2'=>'ប្រតិបត្តិការអចលនៈទ្រព្យផ្សេងៗទៀត'],
            ['job_code'=>'1176','job_title_1'=>'Other renting and leasing','job_title_2'=>'អាជីវកម្មជួល និងភតិសន្យាផ្សេងៗទៀត'],
            ['job_code'=>'1075','job_title_1'=>'Other repair shop','job_title_2'=>'សេវាជួសជុលផ្សេងៗទៀត'],
            ['job_code'=>'1174','job_title_1'=>'Other supporting services','job_title_2'=>'សេវាកម្មផ្សេងៗគាំទ្រដល់សណ្ឋាគារ និងភោជនីដ្ឋាន'],
            ['job_code'=>'1097','job_title_1'=>'Other trading import','job_title_2'=>'នាំចូលទំនិញ/សម្ភារៈផ្សេងៗទៀត'],
            ['job_code'=>'1098','job_title_1'=>'Other trading-export','job_title_2'=>'នាំចេញទំនិញ/សម្ភារៈផ្សេងៗទៀត'],
            ['job_code'=>'1123','job_title_1'=>'Other​ trading retail','job_title_2'=>'លក់រាយផ្សេងៗទៀត'],
            ['job_code'=>'1243','job_title_1'=>'Others non metallic minerals Manu','job_title_2'=>'សិប្បកម្មផលិតសម្ភារៈមិនមែនលោហៈធាតុផ្សេងទៀត'],
            ['job_code'=>'1107','job_title_1'=>'Paddy trading retail','job_title_2'=>'លក់រាយស្រូវ'],
            ['job_code'=>'1151','job_title_1'=>'Paddy trading wholesale','job_title_2'=>'លក់ដុំស្រូវ'],
            ['job_code'=>'1185','job_title_1'=>'Paddy/rice trading-export','job_title_2'=>'នាំចេញស្រូវ/អង្ករ'],
            ['job_code'=>'1161','job_title_1'=>'Paper product processing','job_title_2'=>'សិប្បកម្មផលិតក្រដាស'],
            ['job_code'=>'1167','job_title_1'=>'Pawn shop','job_title_2'=>'សេវាកម្មហាងបញ្ចំ'],
            ['job_code'=>'1078','job_title_1'=>'Peanut production','job_title_2'=>'ធ្វើចំការសណ្តែកដី'],
            ['job_code'=>'1081','job_title_1'=>'Pepper plantation','job_title_2'=>'ធ្វើចំការម្រេច'],
            ['job_code'=>'1077','job_title_1'=>'Phone shop-retail','job_title_2'=>'លក់ទូរស័ព្ទ'],
            ['job_code'=>'1138','job_title_1'=>'Photo shop','job_title_2'=>'សេវាថតរូប និងផ្តិតរូប'],
            ['job_code'=>'1221','job_title_1'=>'Pig trading retail','job_title_2'=>'ជួញជ្រូក'],
            ['job_code'=>'1169','job_title_1'=>'Printing','job_title_2'=>'សេវាកម្មបោះពុម្ព'],
            ['job_code'=>'1155','job_title_1'=>'Private Teacher/Lecturer','job_title_2'=>'គ្រូបង្រៀន/សាស្រ្តាចារ្យ ឯកជន'],
            ['job_code'=>'1064','job_title_1'=>'Private Zoos/Pet stores/Breaders/Safari','job_title_2'=>'សួនសត្វឯកជន/ហាងលក់សត្វចិញ្ចឹម/បង្កាត់ពូជសត្វ/សាហ្វារី'],
            ['job_code'=>'1057','job_title_1'=>'Public Notary','job_title_2'=>'សាការីសាធារណៈ'],
            ['job_code'=>'1040','job_title_1'=>'Public Servant Officer','job_title_2'=>'មន្រ្តីមុខងារសាធារណៈ (រួមមាន  គ្រូបង្រៀន គ្រូពេទ្យរដ្ឋ ជាដើម) '],
            ['job_code'=>'1065','job_title_1'=>'Publishing of books/Dict/brochures','job_title_2'=>'សេវាបោះពុម្ពសៀវភៅ/វចនានុក្រម/ប័ណ្ណផ្សព្វផ្សាយផ្សេងៗ'],
            ['job_code'=>'1244','job_title_1'=>'Publishing of newspapers/journals','job_title_2'=>'សេវាបោះពុម្ពកាសែត/ទស្សនាវដ្តី...'],
            ['job_code'=>'1063','job_title_1'=>'Real Estate Agent/Company','job_title_2'=>'ជំនួញដី (លក់ គួកជេរ) ភ្នាក់ងារ ឬក្រុមហ៊ុនទិញលក់អចលនទ្រព្យ'],
            ['job_code'=>'1247','job_title_1'=>'Renting Equip/machine for Non Agri','job_title_2'=>'អាជីវកម្មជួលសម្ភារៈ/ឧបករណ៍សំរាប់សេវាមិនមែនកសិកម្ម'],
            ['job_code'=>'1237','job_title_1'=>'Renting harvesting machine-Agri','job_title_2'=>'អាជីវកម្មសេវាកម្មជួលម៉ាស៊ីនច្រូតស្រូវ'],
            ['job_code'=>'1218','job_title_1'=>'Renting other agri equipment','job_title_2'=>'អាជីវកម្មជួលសម្ភារៈ/ឧបករណ៍កសិកម្មផ្សេងៗ'],
            ['job_code'=>'1119','job_title_1'=>'Renting tractors-Agri','job_title_2'=>'អាជីវកម្មសេវាកម្មជួលត្រាក់ទ័រ'],
            ['job_code'=>'1153','job_title_1'=>'Renting vehicle','job_title_2'=>'អាជីវកម្មជួលយានយន្ត'],
            ['job_code'=>'1101','job_title_1'=>'Residential leasor','job_title_2'=>'មុខរបរជួលផ្ទះ/បន្ទប់/ខុនដូ...'],
            ['job_code'=>'1262','job_title_1'=>'Retire','job_title_2'=>'អ្នកចូលនិវត្តន៍'],
            ['job_code'=>'1158','job_title_1'=>'Rice mill','job_title_2'=>'រោងម៉ាស៊ីនកិនស្រូវ'],
            ['job_code'=>'1120','job_title_1'=>'Rice milling services','job_title_2'=>'សេវាកម្មម៉ាស៊ីនកិនស្រូវ'],
            ['job_code'=>'1189','job_title_1'=>'Ricksaw/Tuk Tuk','job_title_2'=>'ទិញម៉ូតូកង់បី'],
            ['job_code'=>'1083','job_title_1'=>'Rubber plantation','job_title_2'=>'ធ្វើចំការកៅស៊ូ'],
            ['job_code'=>'1074','job_title_1'=>'Rubber processing','job_title_2'=>'សិប្បកម្មកែច្នៃជ័រកៅស៊ូ'],
            ['job_code'=>'1214','job_title_1'=>'Salt production','job_title_2'=>'ផលិតអំបិល'],
            ['job_code'=>'1215','job_title_1'=>'Sand dredging','job_title_2'=>'បូមខ្សាច់'],
            ['job_code'=>'1131','job_title_1'=>'School/training centre','job_title_2'=>'សេវាកម្មសាលាបង្រៀន/បណ្តុះបណ្តាល'],
            ['job_code'=>'1111','job_title_1'=>'Scrap trading retail','job_title_2'=>'ជួញអេតចាយ'],
            ['job_code'=>'1067','job_title_1'=>'Sculp/painting/handicraft souvenir','job_title_2'=>'សិប្បកម្មផលិតរូបចម្លាក់/គំនូ/វត្ថុអនុស្សាវរីយ៍'],
            ['job_code'=>'1080','job_title_1'=>'Sculp/painting/handicraft souvenir TR','job_title_2'=>'លក់រូបចម្លាក់/គំនូ/វត្ថុអនុស្សាវរីយ៍'],
            ['job_code'=>'1071','job_title_1'=>'Sea fish raising','job_title_2'=>'ចិញ្ចឹមមច្ឆាទឹកប្រៃ'],
            ['job_code'=>'1254','job_title_1'=>'Sea fishing','job_title_2'=>'នេសាទទឹកប្រៃ'],
            ['job_code'=>'1190','job_title_1'=>'Sea fishing trading retail','job_title_2'=>'ជួញផលនេសាទទឹកប្រៃ'],
            #N/A
            ['job_code'=>'1037','job_title_1'=>'Senior government officer','job_title_2'=>'មន្ត្រីជាន់ខ្ពស់នៃរាជរដ្ឋាភិបាល (​រាប់ចាប់ អនុរដ្ឋលេខាធិការ និង រដ្ឋមន្ត្រី)'],
            ['job_code'=>'1038','job_title_1'=>'Senior judicial officer ','job_title_2'=>'មន្ត្រីយុតិ្តធម៌ជាន់ខ្ពស់ រួមមាន (ចៅក្រម ព្រះរាជអាជ្ញា ក្រឡាបញ្ជី)'],
            ['job_code'=>'1048','job_title_1'=>'Senior Politician','job_title_2'=>'មន្ត្រីជាន់ខ្ពស់ផ្នែកនយោបាយ  (ដូចជាប្រធាន អនុប្រធាន​ សមាជិក រដ្ឋសភា និង ព្រឹទ្ធសភា)'],
            ['job_code'=>'1085','job_title_1'=>'Sesame production','job_title_2'=>'ធ្វើចំការល្ង'],
            ['job_code'=>'1164','job_title_1'=>'Site preparation service','job_title_2'=>'សេវារៀបចំដីធ្លី'],
            ['job_code'=>'1191','job_title_1'=>'Soil Trans hauling service','job_title_2'=>'សេវាកម្មដឹកដីលក់'],
            ['job_code'=>'1116','job_title_1'=>'Soya bean production','job_title_2'=>'ធ្វើចំការសណ្តែកសៀង'],
            ['job_code'=>'1228','job_title_1'=>'Spare part for vehicle-retail','job_title_2'=>'លក់គ្រឿងបន្លាស់យានយន្ត'],
            ['job_code'=>'1251','job_title_1'=>'Stationery/office Equip/furniture T','job_title_2'=>'លក់សម្ភារៈ/បរិក្ខារការិយាល័យ/គ្រឿងសង្ហារឹម'],
            ['job_code'=>'1216','job_title_1'=>'Stone crasher','job_title_2'=>'វាយថ្មលក់'],
            ['job_code'=>'1263','job_title_1'=>'Student','job_title_2'=>'សិស្ស/និស្សិត'],
            ['job_code'=>'1127','job_title_1'=>'Sugar cane production','job_title_2'=>'ធ្វើចំការអំពៅ'],
            ['job_code'=>'1070','job_title_1'=>'Sugar processing','job_title_2'=>'ផលិតស្ករត្នោត'],
            ['job_code'=>'1139','job_title_1'=>'Tailor','job_title_2'=>'ជាងកាត់ដេរសំលៀកបំពាក់'],
            ['job_code'=>'1117','job_title_1'=>'Taxi','job_title_2'=>'រថយន្តរត់ឈ្នួលគ្រប់ប្រភេទ'],
            ['job_code'=>'1182','job_title_1'=>'Tour Agency/guide/company','job_title_2'=>'ក្រុមហ៊ុន/ភ្នាក់ងារទេសចរ'],
            ['job_code'=>'1238','job_title_1'=>'Trade of commercial real estate','job_title_2'=>'ជួញអចលនៈទ្រព្យក្នុងវិស័យពាណិជ្ជកម្ម'],
            ['job_code'=>'1239','job_title_1'=>'Trade of residential real estate','job_title_2'=>'ជួញអចលនៈទ្រព្យសម្រាប់លំនៅដ្ឋាន'],
            ['job_code'=>'1150','job_title_1'=>'Traditional medicine TR','job_title_2'=>'លក់ឪសថបុរាណ'],
            ['job_code'=>'1250','job_title_1'=>'Tree nursery and flower production','job_title_2'=>'ដាំផ្កា និង/ឬ​ បណ្តុះកូនឈើ'],
            ['job_code'=>'1192','job_title_1'=>'Tree nursery and flower TR','job_title_2'=>'លក់រាយកូនឈើ/ផ្កា'],
            ['job_code'=>'1261','job_title_1'=>'Unemployed','job_title_2'=>'អ្នកអត់ការងារធ្វើ'],
            ['job_code'=>'1118','job_title_1'=>'Vegetable production','job_title_2'=>'ដាំបន្លែ'],
            ['job_code'=>'1166','job_title_1'=>'Vegetable trading import','job_title_2'=>'នាំចូលបន្លែ'],
            ['job_code'=>'1165','job_title_1'=>'Vegetable trading retail','job_title_2'=>'លក់រាយបន្លែ'],
            ['job_code'=>'1210','job_title_1'=>'Vegetable trading-wholesale','job_title_2'=>'ជួញដុំបន្លែ'],
            ['job_code'=>'1133','job_title_1'=>'Vehicle accessories TI','job_title_2'=>'នាំចូលគ្រឿងបន្លាស់យានយន្ត'],
            ['job_code'=>'1136','job_title_1'=>'Vehicle trading import','job_title_2'=>'នាំចូលយានយន្ត'],
            ['job_code'=>'1140','job_title_1'=>'Vehicle trading retail','job_title_2'=>'ជួញយានយន្ត'],
            ['job_code'=>'1130','job_title_1'=>'Vehicle/tractor making','job_title_2'=>'សិប្បកម្មកែច្នៃយានយន្ត/ត្រាក់ទ័រ'],
            ['job_code'=>'1129','job_title_1'=>'Water supplier','job_title_2'=>'ផ្គត់ផ្គង់ និងចែកចាយទឹក'],
            ['job_code'=>'1177','job_title_1'=>'Water Trans service-goods','job_title_2'=>'សេវាដឹកជញ្ជូនទំនិញតាមផ្លូវទឹក'],
            ['job_code'=>'1128','job_title_1'=>'Watermelon production','job_title_2'=>'ធ្វើចំការឪឡឹក'],
            ['job_code'=>'1259','job_title_1'=>'Weaving mat/pillow/sofa/mattress TR','job_title_2'=>'លក់រាយកន្ទេល ពូក ខ្នើយ'],
            ['job_code'=>'1134','job_title_1'=>'Welding/lathe operator','job_title_2'=>'ផ្សារដែក/ជាងក្រឡឹង'],
            ['job_code'=>'1202','job_title_1'=>'Wet season rice production','job_title_2'=>'ធ្វើស្រែវស្សា'],
            ['job_code'=>'1060','job_title_1'=>'White collar worker ','job_title_2'=>'និយោជិក'],
            ['job_code'=>'1053','job_title_1'=>'Wildlife protection agencies','job_title_2'=>'ភ្នាក់ងារអភិរក្សសត្វព្រៃ'],
            ['job_code'=>'1220','job_title_1'=>'Wine processing','job_title_2'=>'ផលិតស្រា'],
            ['job_code'=>'1147','job_title_1'=>'Wood product processing','job_title_2'=>'សិប្បកម្មផលិតផលិតផលពីឈើ'],
            ['job_code'=>'1093','job_title_1'=>'Wood trading retail','job_title_2'=>'ដេប៉ូលក់ឈើ']
        ]);
    }
}
